### ISSUE TITLE
Project structure and dependencies

### ISSUE THREAD

**Issue by profix898** [ASCOMInitiative/ASCOMLibrary#23]
I had just started to implement my own ASCOM Alpaca client when I found your efforts on Github/NuGet. Thanks for starting this initiative. I want to comment on a few things I noticed during my initial review:

1) ASCOM.Alpaca.Components depends on Newtonsoft.Json (but it also depends on ASCOM.Tools, which in turn depends on System.Text.Json). So you end up having both Newtonsoft.Json and System.Text.Json.

2. ASCOM.Tools comes with a native library (SOFA) which is problematic for true cross-platform use (Mobile, WASM, etc.). Why is SOFA needed for a device interface/client? From my point of view, all such calculations should be either in a separate library or be provided by the consuming library/app.
At least ASCOM.Common.Components is no-dependency library that can be used as a basis for custom implementation. However, I think you should keep native binaries out, otherwise it defies the purpose of your implementation as a universally applicable ASCOM Alpaca base.

3) Also the use of RestSharp seems like a strange trade-off. Yes, RestSharp is easy to use, but actually (at least for .NET5+) HttpClient requires just a few extra lines of code for the same result (but obviously without the dependency). My point is that some people may choose RestSharp, but some dont and those (like me) would like to avoid any extra dependency. This is especially true for mobile/WASM scenarios where any extra library weights in by increasing the footprint of the final app.

4) I also noticed that the package structure is different from the source tree structure. For example, Nuget "ASCOM.Common.Components" does not have a corresponding folder. Same is true for several other packages. That's not a problem per se, but makes it much more difficult to "dive in".

Just some (subjective) thoughts ...

**Comment by Peter-Simpson** [comment]
Hi Thilo,

Thanks very much for your thoughtful feedback. This is a good time because we still consider the library to be in beta status and so could be subject to significant change.

**NewtonSoft and RestSharp** I agree that we shouldn't have dependencies on these. They came in because the code was ported from a .NET 3.5 ASCOM Platform component that can't use System.Text.Json and because RestSharp is just very easy to use. I'll see what we need to do to remove these dependencies.

**SOFA** SOFA is there as a convenience for less experienced users and it also powers the easy to use Transform component. Transform in particular has proved popular with Platform developers because of its straightforward interface. It is currently implemented for Windows, Linux, Arm and MacOS so already has a broad coverage of desktop environments. I agree that it isn't available for mobile environments such as IOS and Android but this may come at a later date if there is sufficient demand.

It is probably the case that we should add OS checks to clarify which OS's the library supports.

Package Structure What would you suggest? Rename the ASCOM.Common folder to ASCOM.Components?

A Few days ago we created a closed Groups.IO discussion group to provide a forum to discuss library features. Would you be interested in an invitation? If so We'll need to exchange your email address in some fashion.

Best wishes, Peter

**Comment by Peter-Simpson** [comment]
Hi Thilo,

I've had a further look at the Alpaca client code and System.Text.Json is already the primary deserialiser. However, I had to retain NewtonSoft in order to deserialise the 2D and 3D arrays that are returned by ICamera.ImageArray and ICamera.ImageArrayVariant.

I continue to be shocked that System.Text.Json can not handle arrays other than 1D: [Supported collection types in System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-supported-collection-types?pivots=dotnet-6-0).

Do you know any way around this?

Thanks, Peter

**Comment by profix898** [comment]
I would generally suggest a strictly layered approach (which should be reflected in the package naming schema).

L1: Interfaces (ICamera, ITeleskop, etc.) = ASCOM.Common.Components
L2: Low-level client (L1 + HttpClient + Timing/Exceptions, etc.)
L3: High-level client (L2 + high-level functionality, such as coordinate transforms, etc.)

With L1 you only get the API contract (interfaces, enums, ...). So that you can implement your own client/device. With L2 you get access to all device functionality including communication and error handling. L3 only adds convinience features (for common scenarios) which may require additional (external) libraries. Not sure how much L3 is really needed here though.

Same for server-side. L2 only provides 1:1 device abstraction in ASCOM interfaces plus the communication. L3 could provide stub implementations for typical devices, e.g. a TelescopeBase for everyone trying to implement ITeleskope for their own devices, etc.

I know that I'm personally very picky when it comes to external dependencies (especially if it involves native(!) binaries). That said, I think a library like yours, which positions itself as a foundational layer for .NET-based ASCOM/Alpaca clients and devices should be equally consious about its dependencies or avoid them altogether. The .NET ecosystem is always evolving. The choices you make for your depedencies should still be valid in a few years (see Newtonsoft.Json).

Its no different with SOFA. SOFA is a quasi-standard, yes, but still many people use AA+ or alternatives. Also, SOFA takes a very opinionated approach (with cryptic function names). I guess the main point is that ASCOM/Alpaca is for device communication, SOFA is for "math". You should be able to pick one without the other.

My suggested naming would be something like
ASCOM.Common (or ASCOM.Abstraction or ASCOM.Interfaces)
ASCOM.Alpaca.Client (depends on ASCOM.Common only)
ASCOM.Alpaca.Device (depends on ASCOM.Common only)
ASCOM.Utility

No separate ASCOM.Exception.Library, add to ASCOM.Common.

Put high-level helpers, such as Transform, into new ASCOM.Utility (or keep ASCOM.Tools as name, and move content around). If there is high-level functionality for client/device, consider ASCOM.Alpaca.Client/Device.Extensions (or something like that).

ASCOM.Tools contains configuration and logging support which nowadays is superseded by DI components for most people anyway (think host builder pattern with IServiceProvider/ILogger/IOptions). Use standard interfaces as much as possible. This also gives a flexibility to choose a suitable components from NuGet (Serilog, etc.).

Just my two cents ... ;)

Groups.IO: At this point I'm speaking from the perspective of a hobby project. And ASCOM Alpaca is just starting to become of serious interest to my implementation. However, if you feel that my limited feedback on a separate discussion channel would be helpful, let me know. I could post my email address (and then delete/edit the post shortly afterwards).

**Comment by profix898** [comment]
JSON itself does not support multi-dimensional arrays!! It only supports arrays of arrays (what is called jagged arrays in C#) and these are supported in System.Text.Json. If you want to store 2D arrays, you have to convert to jagged arrays at some point anyway.
Option 1: Jagged arrays are supported with System.Text.Json. Use jagged arrays and convert from/to 2D (by using BlockCopy or Span.CopyTo).

However, it would be more efficient to use memory pooling instead of direct allocation for image buffers. Therefore, Option 2 would be to use 1D arrays internally for everything (incl. serialization), but expose them as 2D arrays (for example as Span2D). Real 2D arrays are contiguous in memory in .NET (typically with row-major order), so in memory there is essentially no difference (you could even do unsafe tricks to treat one as the other).

What element type for the image buffer would you like? Int/Double or RGBx structs?

**Comment by Peter-Simpson** [comment]
Hi Thilo,

Thanks for your insight about JSON using jagged arrays. I've just resolved my final issue of how to copy data efficiently from the deserialised jagged array to the required 2D or 3D regular array. Buffer.BlockCopy is blazing fast and I've wrapped that inside a Parallel.For loop to handle the outer dimension.

The nett result is that deserialisation is now about 4 times faster than NewtonSoft, despite having the additional data copy step from jagged to regular array.  I'm pleased to say that the NewtonSoft dependency is now gone!

I'm now going to have a look at removing RestSharp too.

Best wishes, Peter

**Comment by profix898** [comment]
Awesome! Good to know that I didnt make trouble for nothing ;)
Looking forward to testing the new beta soon.

**Comment by Peter-Simpson** [comment]
Hi Thilo,

RestSharp is now gone too so there are no longer any third party components in the library. I posted beta 4 last night.

Best wishes, Peter

**Comment by profix898** [comment]
Hi Peter,

that's really great news! I just created a fork to experiment with your repo/project.

I already removed the ASCOM.Tools dependency in the other libraries by using ILogger from Microsoft.Extensions.Logging(.Abstractions). ConsoleLogger and TraceLogger are a no-brainer then (just pick a logging package of your choice, e.g. Serilog, NLog, etc.). ASCOM.Tools is now only there as an "extension" package containing Sofa, Transform* types, etc.

Next, I would like to make it more DI-friendly (especially PlatformUtilities), so that e.g. ILogger can be injected/provided by the consuming app/lib, instead of being hardcoded.

Note: I found that ASCOM.Alpaca contains an invalid package reference to 'ASCOM.Exceptions'.

I will be away for a conference over the next week. Will "experiment" a little more then and let you know what I find ...

Best, Thilo

**Comment by Peter-Simpson** [comment]
Thanks Thilo, I hope you enjoy the conference. I couldn't see the invalid package here, presumably because there was a copy in my local NuGet cache. Anyway, it's fixed now in beta 8, together with some small issues in the Alpaca client code.

I need an email address in order to invite you to the library test group, please can you PM me if you would still like to participate.

Best wishes, Peter

**Comment by profix898** [comment]
Hi Peter,

I tried to make a minimal-changes version of the latest beta that still removes the dependency in _ASCOM.Alpaca_ and _ASCOM.Com_ from _ASCOM.Tools_. For that, I introduced a new _ITraceLogger_ (in _ASCOM.Common.Interfaces_) resembling the public interface of _TraceLogger_ in _Tools_.

Since _PlatformUtilities_ had a hard-coded _TraceLogger_ dependency, I created a new public static field '_TraceLogger_' that can be set to any _ITraceLogger_ instance and is used to propagate all internal log messages from _PlatformUtilities_. The field defaults to a newly created _NullLogger_ (which does not do anything). To restore the previous behaviour, one would use a one-liner of custom initialization: `PlatformUtilities.TraceLogger = new TraceLogger();`.

With these changes I can now use Alpaca (or Com) client without Tools dependency. As mentioned before, I don't like the Sofa library in my project nor do I plan to use any of the built-in logging functionality in _ASCOM.Tools_.

I think that with these simple changes you can still use everything as before, but it is now possible to skip ASCOM.Tools altogether, making it completely optional. Also, it is easy to use a custom I(Trace)Logger instead of TraceLogger (from Tools). This gives us flexibility of pointing the logger somewhere else, e.g. to EventLog, network service, etc. Also, redirecting to MS ILogger, Serilog, etc. requires only a trivial adapter class.

Usually, I would probably refactor more and rely on MS ILogger as a standard interface. But I though to keep as close as possible to the current state of the project.

I hope you can follow my intention here. Let me know what you think.

#24 is the related PR with the changes for discussion.

Regards
Thilo

**Comment by profix898** [comment]
Hi Peter,

I tried to make a minimal-changes version of the latest beta that still removes the dependency in _ASCOM.Alpaca_ and _ASCOM.Com_ from _ASCOM.Tools_. For that, I introduced a new _ITraceLogger_ (in _ASCOM.Common.Interfaces_) resembling the public interface of _TraceLogger_ in _Tools_.

Since _PlatformUtilities_ had a hard-coded _TraceLogger_ dependency, I created a new public static field '_TraceLogger_' that can be set to any _ITraceLogger_ instance and is used to propagate all internal log messages from _PlatformUtilities_. The field defaults to a newly created _NullLogger_ (which does not do anything). To restore the previous behaviour, one would use a one-liner of custom initialization: `PlatformUtilities.TraceLogger = new TraceLogger();`.

With these changes I can now use Alpaca (or Com) client without Tools dependency. As mentioned before, I don't like the Sofa library in my project nor do I plan to use any of the built-in logging functionality in _ASCOM.Tools_.

I think that with these simple changes you can still use everything as before, but it is now possible to skip ASCOM.Tools altogether, making it completely optional. Also, it is easy to use a custom I(Trace)Logger instead of TraceLogger (from Tools). This gives us flexibility of pointing the logger somewhere else, e.g. to EventLog, network service, etc. Also, redirecting to MS ILogger, Serilog, etc. requires only a trivial adapter class.

öUsually, I would probably refactor some more and rely on MS ILogger as a standard interface.

I hope you can follow my intention here. Let me know what you think.

#24 is a PR with the changes for discussion.

Regards
Thilo

**Comment by profix898** [comment]
@Peter-Simpson: I can't find a PM option on your profile. Please use 'astronomy@profix898.de' for the library testing group.

**Comment by profix898** [comment]
Closing as completed (in 1.0.0-beta10).
