### ISSUE TITLE
Driver Access focuser class trys to set 'Connected' on an InterfaceVersion=1 focuser due to missing 'return'

### ISSUE THREAD

**Issue by rwg0** [ASCOMInitiative/ASCOMLibrary#26]
Very simple - there should be a return after the line linked below so that for interface version=1 drivers, the code just sets 'Link' rather than trying to also set 'Connected' and failing

https://github.com/ASCOMInitiative/ASCOMLibrary/blob/ba3decad5afc7c6c2068a0aff0d1359bfa7f00f5/ASCOM.Com/ASCOM.Com.DriverAccess/Focuser.cs#L45

**Comment by DanielVanNoord** [comment]
Thanks, it has been fixed. Should make the next release.
