### ISSUE TITLE
ASCOMLibrary does not accept JSON response from indigo_alpaca_agent (which works with ASCOM Platform)

### ISSUE THREAD

**Issue by rwg0** [ASCOMInitiative/ASCOMLibrary#30]
indigo_alpaca_agent produces JSON responses to /configureddevices that ASCOMLibrary does not accept. For example it creates the following response

```{ "Value": [ { "DeviceName": "Altair ALTAIRGP130M (guider)", "DeviceType": "Telescope", "DeviceNumber": "1", "UniqueID": "775684E2-D406-4B47-8372-3362E338B455" }, { "DeviceName": "Altair ALTAIRGP130M", "DeviceType": "Camera", "DeviceNumber": "0", "UniqueID": "775684E2-0797-4225-8415-9554D475B455" }, { "DeviceName": "Mount Simulator (guider)", "DeviceType": "Telescope", "DeviceNumber": "3", "UniqueID": "47B431C1-E184-493C-8184-C73776B76797" }, { "DeviceName": "Mount Simulator", "DeviceType": "Telescope", "DeviceNumber": "2", "UniqueID": "2567C757-B722-4850-8747-C73776B76797" }, ], "ClientTransactionID": 0, "ServerTransactionID": 68 }```

The problems here are that the "DeviceNumber" should be an integer not a string and that the trailing comma is rejected in the array of devices.

However, the same JSON is accepted by the ASCOM Platform's Alpaca code, and the indigo code was set up to work correctly with the ASCOM Platform, in spite of being strictly not compatible with the Alpaca API spec (see https://github.com/indigo-astronomy/indigo/issues/504)

We should make the ASCOMLibrary JSON handling more forgiving to accept the current response of the indigo_alpaca_agent code (this is simple to do via options to the JSON serializer).

**Comment by Peter-Simpson** [comment]
Closing this issue because #31 is now closed.
