### ISSUE TITLE
NullReferenceException being thrown from DynamicAccess.CheckDotNetExceptions

### ISSUE THREAD

**Issue by rwg0** [ASCOMInitiative/ASCOMLibrary#34]
I have an error reporting system in SharpCap and it has picked up a number of 'in the wild' cases where the code of DynamicAccess.CheckDotNetExceptions is throwing a NullReferenceException. It took me a while to notice that this is a NullReferenceException due to an issue in the exception handling code - not a NullReferenceException coming from the ASCOM driver.

The most likely cause looks to be the fall-through case, which would throw if the exception being handled does not have an InnerException. Interestingly, at the top of the method, when setting the HResult the code does deal with a null InnerException, so this must have been a consideration at some point but didn't carry through the whole method.

Since the current issue is blocking the true information about the initial exception from being propagated upwards, it's important to fix this. I have prepared a 'minimum impact' pull request for this that deals with the most likely case at line 261 and also a more theoretical case at lines 175-177. The statements guarded by checks on the HResult should be fine as the HResult is zero if the inner exception is null.

One other thing to note is that fetching the message from the InnerException may not be sufficient to extract the underlying cause of the failure... In some cases the InnerExceptions may nest several layers deep. An extension method like this can come in handy, but that's something that requires more consideration.

```
        public static Exception InnermostException(this Exception target)
        {
            return target.InnerException?.InnermostException() ?? target;
        }
```

**Comment by Peter-Simpson** [comment]
I'm closing this because pull request '35 has been accepted and merged into the code base.
